export default {
  LOGGER: Symbol('LOGGER'),
  AUTHENTICATION_INFO_PROVIDER: Symbol('AUTHENTICATION_INFO_PROVIDER'),
  API_KEY_INFO_PROVIDER: Symbol('API_KEY_INFO_PROVIDER'),
  LINKS: Symbol('LINKS'),
  VIEW_PROPS: Symbol('VIEW_PROPS'),
}
