export default {
  CONTROLLER_ROUTES: Symbol('controller:routes'),
  CONTROLLER: Symbol('controller'),
  LOGGER: Symbol('logger'),
  AUTHENTICATION_INFO_PROVIDER: Symbol('authentication:info:provider'),
  API_KEY_INFO_PROVIDER: Symbol('apikey:info:provider'),
  LINKS: Symbol('links'),
  VIEW_P: Symbol('ha'),
  VIEW_PROPS: Symbol('view:properties'),
  VIEW_ARRAY_PROPS: Symbol('view:array:properties'),
  VALIDATION_PROPERTIES_METADATA: Symbol('validation:properties:metadata'),
  VALIDATION_CLASS_METADATA: Symbol('validation:class:metadata'),
  VALIDATION_CLASS_METADATA_COLLECTION: Symbol('validation:class:metadata:collection'),
  DEFAULT_MEDIA_TYPE: 'application/json',
}
